"""Railway simulation core for the AI train traffic control prototype.

Time model
----------
Every timestamp in this module is an **integer number of minutes measured from**
``BASE_MINUTE`` (10:00 local time).  :func:`format_minute` converts such a value
back into a human readable ``HH:MM`` label for the API / UI layer.

What lives here
---------------
1. The topology of the single corridor prototype (stations, blocks, trains).
2. The *booked* baseline timetable, generated by the rule based planner
   :func:`plan_rule_based` so that the booked plan is guaranteed conflict free.
3. The disruption model:

   * :func:`propagate_legacy` -- the legacy single hop delay propagation rule
     that represents "what happens if the dispatcher does not intervene":
     the disrupted train and the *immediate* follower inherit a linear shift
     while trains further downstream are missed, which leaves real conflicts.
   * :func:`plan_rule_based` -- the same rule engine but with every physical
     constraint enforced (first come first served with clamps).  This is the
     fallback plan the CP-SAT optimizer is benchmarked against.

Disclaimer
----------
Decision-support / simulation prototype.  It never issues movement authorities
to real trains -- every resume signal is a recommendation for a human dispatcher.
"""

from __future__ import annotations

import copy
from typing import Any, Dict, List, Optional, Sequence

# ---------------------------------------------------------------------------
# Global constants
# ---------------------------------------------------------------------------

#: ``t = 0`` corresponds to 10:00 local time.
BASE_MINUTE = 10 * 60

#: Minimum headway (minutes) that must separate two consecutive trains inside
#: the same block, measured from the rear train exit to the next train entry.
MIN_HEADWAY_MIN = 3

#: Shortest station stop a dispatcher may authorise (used by the optimizer to
#: claw back delay without running trains ahead of their booked path).
MIN_DWELL_MIN = 1

#: Longest station hold the optimizer is allowed to plan (minutes).
MAX_HOLD_MIN = 90

#: Planning horizon used by the CP-SAT model (minutes after 10:00).
HORIZON_MIN = 240

# ---------------------------------------------------------------------------
# Topology -- a single corridor:  A -> BL1 -> B -> BL2 -> C -> BL3 -> D
# ---------------------------------------------------------------------------

STATIONS: List[Dict[str, Any]] = [
    {"id": "A", "name": "Central Junction", "code": "A", "platforms": 3, "km": 0.0},
    {"id": "B", "name": "Northgate", "code": "B", "platforms": 2, "km": 14.0},
    {"id": "C", "name": "Riverside", "code": "C", "platforms": 2, "km": 31.0},
    {"id": "D", "name": "Harbour Terminus", "code": "D", "platforms": 3, "km": 47.0},
]

BLOCKS: List[Dict[str, Any]] = [
    {"id": "BL1", "name": "Block 1", "from": "A", "to": "B", "length_km": 14.0},
    {"id": "BL2", "name": "Block 2", "from": "B", "to": "C", "length_km": 17.0},
    {"id": "BL3", "name": "Block 3", "from": "C", "to": "D", "length_km": 16.0},
]

#: Every train runs the same (down) direction in this prototype.
ROUTE_BLOCK_IDS: List[str] = [block["id"] for block in BLOCKS]

#: Stations that sit between two blocks -- trains can be held here.
INTERMEDIATE_STATION_IDS: List[str] = [block["to"] for block in BLOCKS[:-1]]

STATION_BY_ID: Dict[str, Dict[str, Any]] = {s["id"]: s for s in STATIONS}
BLOCK_BY_ID: Dict[str, Dict[str, Any]] = {b["id"]: b for b in BLOCKS}

TRAIN_COLOURS = {
    "Express": "#6366f1",
    "Passenger": "#0ea5e9",
    "Freight": "#f59e0b",
}

TRAINS: List[Dict[str, Any]] = [
    {
        "id": "T101",
        "name": "Rajdhani Express",
        "type": "Express",
        "priority": 1,
        "weight": 3,
        "departure": 0,
        "run_min": {"BL1": 5, "BL2": 6, "BL3": 5},
        "dwell_min": {"B": 1, "C": 1},
    },
    {
        "id": "T204",
        "name": "Intercity Passenger",
        "type": "Passenger",
        "priority": 3,
        "weight": 2,
        "departure": 15,
        "run_min": {"BL1": 6, "BL2": 7, "BL3": 6},
        "dwell_min": {"B": 2, "C": 3},
    },
    {
        "id": "T305",
        "name": "Coal Freight 305",
        "type": "Freight",
        "priority": 4,
        "weight": 1,
        "departure": 26,
        "run_min": {"BL1": 8, "BL2": 9, "BL3": 8},
        "dwell_min": {"B": 4, "C": 5},
    },
    {
        "id": "T408",
        "name": "Superfast Express",
        "type": "Express",
        "priority": 2,
        "weight": 3,
        "departure": 37,
        "run_min": {"BL1": 5, "BL2": 6, "BL3": 5},
        "dwell_min": {"B": 1, "C": 1},
    },
]

for _train in TRAINS:
    _train["colour"] = TRAIN_COLOURS[_train["type"]]

TRAIN_BY_ID: Dict[str, Dict[str, Any]] = {t["id"]: t for t in TRAINS}

#: Booked order in which trains leave the origin terminal.  Used for the
#: sequence-preservation rule (no overtaking on the single line).
BOOKED_ORDER: List[str] = [t["id"] for t in TRAINS]

DISCLAIMER = "Decision-Support / Simulation Prototype - Not Autonomous Train Control"

# ---------------------------------------------------------------------------
# Time helpers
# ---------------------------------------------------------------------------

def format_minute(minute: int) -> str:
    """Render an integer minute offset as a ``HH:MM`` wall clock label."""
    absolute = BASE_MINUTE + int(round(minute))
    return f"{absolute // 60:02d}:{absolute % 60:02d}"


def format_delay(minute: int) -> str:
    """Render an integer delay in a dispatcher friendly way."""
    if minute <= 0:
        return "on time"
    return f"+{minute} min"


def run_minutes(train_id: str, block_id: str) -> int:
    return TRAIN_BY_ID[train_id]["run_min"][block_id]


def final_arrival(entries_for_train: Dict[str, int], train_id: str) -> int:
    """Arrival at the terminus implied by a train's block entry times."""
    last_block = ROUTE_BLOCK_IDS[-1]
    return entries_for_train[last_block] + run_minutes(train_id, last_block)


# ---------------------------------------------------------------------------
# Schedule construction
# ---------------------------------------------------------------------------

def schedule_from_entries(
    block_entries: Dict[str, Dict[str, int]],
    source: str,
    baseline_entries: Optional[Dict[str, Dict[str, int]]] = None,
) -> Dict[str, Any]:
    """Expand raw ``{train: {block: entry}}`` data into the API schedule shape.

    The payload contains, per train, the occupancy of every block, the arrival /
    departure at every station, the delay of every movement versus the booked
    timetable and the resulting headline numbers used by the KPI cards.
    """
    trains_payload: Dict[str, Any] = {}
    total_delay = 0
    max_delay = 0

    for train in TRAINS:
        train_id = train["id"]
        entries = block_entries[train_id]
        booked = baseline_entries[train_id] if baseline_entries else None

        blocks_payload: Dict[str, Any] = {}
        for block_id in ROUTE_BLOCK_IDS:
            entry = entries[block_id]
            exit_ = entry + run_minutes(train_id, block_id)
            blocks_payload[block_id] = {
                "block_id": block_id,
                "entry": entry,
                "exit": exit_,
                "entry_label": format_minute(entry),
                "exit_label": format_minute(exit_),
                "run_min": run_minutes(train_id, block_id),
                "delay": (entry - booked[block_id]) if booked else 0,
            }

        stations_payload: Dict[str, Any] = {}
        for index, station in enumerate(STATIONS):
            station_id = station["id"]
            if index == 0:
                arrive = depart = entries[ROUTE_BLOCK_IDS[0]]
            elif index == len(STATIONS) - 1:
                arrive = depart = final_arrival(entries, train_id)
            else:
                upstream_block = ROUTE_BLOCK_IDS[index - 1]
                arrive = entries[upstream_block] + run_minutes(train_id, upstream_block)
                depart = entries[ROUTE_BLOCK_IDS[index]]
            dwell = depart - arrive
            planned_dwell = train["dwell_min"].get(station_id, 0)
            stations_payload[station_id] = {
                "station_id": station_id,
                "arrive": arrive,
                "depart": depart,
                "arrive_label": format_minute(arrive),
                "depart_label": format_minute(depart),
                "dwell_min": dwell,
                "planned_dwell_min": planned_dwell,
                "hold_min": max(0, dwell - planned_dwell),
            }

        arrival = final_arrival(entries, train_id)
        booked_arrival = final_arrival(booked, train_id) if booked else arrival
        delay = arrival - booked_arrival
        total_delay += delay
        max_delay = max(max_delay, delay)

        trains_payload[train_id] = {
            "train_id": train_id,
            "name": train["name"],
            "type": train["type"],
            "priority": train["priority"],
            "weight": train["weight"],
            "colour": train["colour"],
            "blocks": blocks_payload,
            "stations": stations_payload,
            "final_arrival": arrival,
            "final_arrival_label": format_minute(arrival),
            "booked_arrival": booked_arrival,
            "booked_arrival_label": format_minute(booked_arrival),
            "final_delay": delay,
            "final_delay_label": format_delay(delay),
        }

    return {
        "source": source,
        "totals": {
            "total_delay_min": total_delay,
            "max_delay_min": max_delay,
            "trains": len(TRAINS),
        },
        "trains": trains_payload,
        "notes": [],
    }

# ---------------------------------------------------------------------------
# Disruption model
# ---------------------------------------------------------------------------

def normalise_disruption(raw: Dict[str, Any]) -> Dict[str, Any]:
    """Validate and normalise an incoming disruption request.

    Two disruption kinds are supported:

    ``signal_delay``
        ``{"type": "signal_delay", "train_id": "T204", "block_id": "BL2",
        "minutes": 15}`` -- the train may not enter the block before its booked
        entry time plus ``minutes``.
    ``block_closure``
        ``{"type": "block_closure", "block_id": "BL3", "start_minute": 20,
        "end_minute": 45}`` -- the block is not available between ``start`` and
        ``end`` (signal failure, track possession, ...).
    """
    dtype = str(raw.get("type") or "signal_delay").strip().lower()

    if dtype in ("delay", "signal_delay", "speed_restriction"):
        train_id = raw.get("train_id")
        block_id = raw.get("block_id")
        minutes = raw.get("minutes", raw.get("delay_minutes"))
        if train_id not in TRAIN_BY_ID:
            raise ValueError(f"unknown train '{train_id}' (expected one of {BOOKED_ORDER})")
        if block_id not in BLOCK_BY_ID:
            raise ValueError(f"unknown block '{block_id}' (expected one of {ROUTE_BLOCK_IDS})")
        try:
            minutes = int(minutes)
        except (TypeError, ValueError):
            raise ValueError("'minutes' must be an integer between 1 and 180") from None
        if not 1 <= minutes <= 180:
            raise ValueError("'minutes' must be between 1 and 180")
        return {
            "type": "signal_delay",
            "train_id": train_id,
            "block_id": block_id,
            "minutes": minutes,
            "label": f"{train_id} +{minutes} min in {block_id}",
            "detail": (
                f"{train_id} may not enter {block_id} before "
                f"{format_minute(_BOOKED_ENTRIES_LAZY()[train_id][block_id] + minutes)}."
            ),
        }

    if dtype in ("closure", "block_closure", "track_closure", "maintenance"):
        block_id = raw.get("block_id")
        if block_id not in BLOCK_BY_ID:
            raise ValueError(f"unknown block '{block_id}' (expected one of {ROUTE_BLOCK_IDS})")
        start = raw.get("start_minute", raw.get("start"))
        end = raw.get("end_minute", raw.get("end"))
        try:
            start, end = int(start), int(end)
        except (TypeError, ValueError):
            raise ValueError("'start_minute' and 'end_minute' must be integers") from None
        if start < 0 or end <= start or end > HORIZON_MIN:
            raise ValueError("'start_minute' must be >= 0 and 'end_minute' > start_minute")
        reason = str(raw.get("reason") or "Track possession / signal failure")
        return {
            "type": "block_closure",
            "block_id": block_id,
            "start": start,
            "end": end,
            "reason": reason,
            "label": f"{block_id} closed {format_minute(start)}-{format_minute(end)}",
            "detail": (
                f"No occupancy of {block_id} {format_minute(start)}-{format_minute(end)}."
            ),
        }

    raise ValueError(f"unknown disruption type '{dtype}'")


def closures_on(disruptions: Sequence[Dict[str, Any]], block_id: str) -> List[Dict[str, Any]]:
    return [
        d for d in disruptions
        if d["type"] == "block_closure" and d["block_id"] == block_id
    ]


def signal_delay_bound(
    disruptions: Sequence[Dict[str, Any]], train_id: str, block_id: str, booked_entry: int
) -> int:
    """Lowest feasible entry time for ``train_id`` entering ``block_id``."""
    lower = booked_entry
    for disruption in disruptions:
        if (
            disruption["type"] == "signal_delay"
            and disruption["train_id"] == train_id
            and disruption["block_id"] == block_id
        ):
            lower = max(lower, booked_entry + disruption["minutes"])
    return lower


def _apply_closure(entry: int, run: int, disruption: Dict[str, Any]) -> int:
    """Push an entry later so the block is clear during a possession window."""
    start, end = disruption["start"], disruption["end"]
    if entry + run <= start or entry >= end:
        return entry  # fits before the window, or already after it
    return max(entry, end)

# ---------------------------------------------------------------------------
# Rule based planning: booked timetable + fallback ("rule engine") plan
# ---------------------------------------------------------------------------

_BASELINE_ENTRY_CACHE: Optional[Dict[str, Dict[str, int]]] = None


def _BOOKED_ENTRIES_LAZY() -> Dict[str, Dict[str, int]]:
    """Late accessor used by the disruption normaliser for readable labels."""
    return build_baseline_entries()


def build_baseline_entries(force: bool = False) -> Dict[str, Dict[str, int]]:
    """Booked block entry times -- generated once and cached (deterministic)."""
    global _BASELINE_ENTRY_CACHE
    if _BASELINE_ENTRY_CACHE is None or force:
        _BASELINE_ENTRY_CACHE = _plan_entries([], compress_dwell=False, booked=None)
    return copy.deepcopy(_BASELINE_ENTRY_CACHE)


def _plan_entries(
    disruptions: Sequence[Dict[str, Any]],
    compress_dwell: bool = False,
    booked: Optional[Dict[str, Dict[str, int]]] = None,
) -> Dict[str, Dict[str, int]]:
    """First come / first served planner used by the rule engine.

    Trains are planned in their booked order.  Every physical constraint is
    enforced (minimum headway per block, minimum station dwell, no running ahead
    of the booked path, disruption bounds) so the plan is always conflict free.
    """
    if booked is None and disruptions:
        raise ValueError("the booked baseline plan cannot carry disruptions")

    block_last_exit: Dict[str, Optional[int]] = {block_id: None for block_id in ROUTE_BLOCK_IDS}
    entries: Dict[str, Dict[str, int]] = {}

    for train in TRAINS:
        train_id = train["id"]
        train_entries: Dict[str, int] = {}
        previous_exit: Optional[int] = None

        for index, block_id in enumerate(ROUTE_BLOCK_IDS):
            run = train["run_min"][block_id]
            if index == 0:
                lower = train["departure"]
            else:
                station_id = STATIONS[index]["id"]
                dwell_floor = MIN_DWELL_MIN if compress_dwell else train["dwell_min"][station_id]
                lower = previous_exit + dwell_floor

            if booked is not None:
                booked_entry = booked[train_id][block_id]
                lower = max(lower, booked_entry)  # never run ahead of the booked path
                lower = max(
                    lower, signal_delay_bound(disruptions, train_id, block_id, booked_entry)
                )

            if block_last_exit[block_id] is not None:
                lower = max(lower, block_last_exit[block_id] + MIN_HEADWAY_MIN)

            for closure in closures_on(disruptions, block_id):
                lower = _apply_closure(lower, run, closure)

            train_entries[block_id] = lower
            previous_exit = lower + run
            block_last_exit[block_id] = previous_exit

        entries[train_id] = train_entries

    return entries


def plan_rule_based(
    disruptions: Sequence[Dict[str, Any]] = (),
    compress_dwell: bool = False,
    source: str = "rule_based",
    booked: Optional[Dict[str, Dict[str, int]]] = None,
) -> Dict[str, Any]:
    """Rule engine plan (deterministic, conflict free) used as the benchmark."""
    booked = build_baseline_entries() if booked is None else booked
    entries = _plan_entries(disruptions, compress_dwell=compress_dwell, booked=booked)
    schedule = schedule_from_entries(entries, source=source, baseline_entries=booked)
    schedule["notes"] = [
        "Rule engine plan: first come / first served, all safety constraints enforced."
    ]
    return schedule


def build_baseline() -> Dict[str, Any]:
    """The booked corridor timetable (conflict free by construction)."""
    booked = build_baseline_entries()
    schedule = schedule_from_entries(booked, source="baseline", baseline_entries=booked)
    schedule["notes"] = ["Booked corridor timetable - conflict free by construction."]
    return schedule

# ---------------------------------------------------------------------------
# Legacy cascade: single hop delay propagation ("no intervention" scenario)
# ---------------------------------------------------------------------------

def _shift_from(train_entries: Dict[str, int], start_index: int, delta: int) -> None:
    """Shift every block entry from ``start_index`` onwards by ``delta`` minutes."""
    for block_id in ROUTE_BLOCK_IDS[start_index:]:
        train_entries[block_id] += delta


def next_booked_train(train_id: str) -> Optional[str]:
    """The train booked immediately behind ``train_id`` on the corridor."""
    index = BOOKED_ORDER.index(train_id)
    return BOOKED_ORDER[index + 1] if index + 1 < len(BOOKED_ORDER) else None


def propagate_legacy(
    disruptions: Sequence[Dict[str, Any]] = (),
    booked: Optional[Dict[str, Dict[str, int]]] = None,
) -> Dict[str, Any]:
    """Legacy cascade: linear, **single hop** delay propagation.

    Delay inheritance follows the explicit dispatcher rule

    ``new_delay = max(0, min_gap - (other_train_time - (delayed_train_time + N)))``

    where ``other_train_time`` is the follower's booked entry into the affected
    block and ``delayed_train_time + N`` is the *revised* moment at which the
    disrupted train clears that block (``N`` = its block running time).

    Only the immediate booked follower reacts, so trains two or more hops
    downstream keep their booked path.  That omission is precisely why the
    cascade plan still contains conflicts and why the CP-SAT re-plan is needed.
    """
    booked = build_baseline_entries() if booked is None else booked
    entries = copy.deepcopy(booked)
    notes: List[str] = []

    for disruption in disruptions:
        if disruption["type"] == "signal_delay":
            train_id = disruption["train_id"]
            block_id = disruption["block_id"]
            minutes = disruption["minutes"]
            index = ROUTE_BLOCK_IDS.index(block_id)
            run = TRAIN_BY_ID[train_id]["run_min"][block_id]

            _shift_from(entries[train_id], index, minutes)
            revised_exit = booked[train_id][block_id] + minutes + run
            notes.append(
                f"{train_id} clears {block_id} {format_minute(revised_exit)} "
                f"(booked {format_minute(booked[train_id][block_id] + run)})."
            )

            follower_id = next_booked_train(train_id)
            if follower_id:
                other_train_time = booked[follower_id][block_id]
                deficit = max(0, MIN_HEADWAY_MIN - (other_train_time - revised_exit))
                if deficit > 0:
                    _shift_from(entries[follower_id], index, deficit)
                    notes.append(
                        f"{follower_id} +{deficit} min behind {train_id}; headway "
                        f"restored {format_minute(revised_exit + MIN_HEADWAY_MIN)}."
                    )
                else:
                    notes.append(
                        f"{follower_id} keeps booked path - headway to {train_id} holds."
                    )
        else:  # block closure
            block_id = disruption["block_id"]
            start, end = disruption["start"], disruption["end"]
            index = ROUTE_BLOCK_IDS.index(block_id)
            affected: List[str] = []

            for train_id in BOOKED_ORDER:
                run = TRAIN_BY_ID[train_id]["run_min"][block_id]
                entry = entries[train_id][block_id]
                if entry + run <= start or entry >= end:
                    continue  # passes before the possession window
                _shift_from(entries[train_id], index, end - entry)
                affected.append(train_id)

            if affected:
                                notes.append(
                    f"{block_id} closed {format_minute(start)}-{format_minute(end)}: "
                    f"{', '.join(affected)} re-planned at {format_minute(end)}."
                )
            else:
                                notes.append(
                    f"{block_id} closed {format_minute(start)}-{format_minute(end)}: "
                    "no booked train affected."
                )

    schedule = schedule_from_entries(entries, source="legacy_cascade", baseline_entries=booked)
    schedule["notes"] = notes
    return schedule

# ---------------------------------------------------------------------------
# Mutable simulation state
# ---------------------------------------------------------------------------

def train_public_payload(train: Dict[str, Any]) -> Dict[str, Any]:
    """Topology view of a train (without any schedule data)."""
    return {
        "id": train["id"],
        "name": train["name"],
        "type": train["type"],
        "priority": train["priority"],
        "weight": train["weight"],
        "colour": train["colour"],
        "origin": STATIONS[0]["id"],
        "destination": STATIONS[-1]["id"],
        "departure": train["departure"],
        "departure_label": format_minute(train["departure"]),
        "booked_total_run_min": sum(train["run_min"].values()) + sum(train["dwell_min"].values()),
        "run_min": dict(train["run_min"]),
        "dwell_min": dict(train["dwell_min"]),
    }


class SimulationState:
    """Single in-memory simulation state shared by all API requests.

    The prototype intentionally keeps its state in memory: it is a
    decision-support sandbox, so a restart simply restores the booked baseline.
    """

    def __init__(self) -> None:
        self.disruptions: List[Dict[str, Any]] = []
        self.sequence = 0
        self.booked: Dict[str, Dict[str, int]] = {}
        self.baseline: Dict[str, Any] = {}
        self.legacy: Dict[str, Any] = {}
        self.rule_based: Dict[str, Any] = {}
        self.optimized: Optional[Dict[str, Any]] = None
        self.solver_info: Optional[Dict[str, Any]] = None
        self.reset()

    # -- lifecycle ---------------------------------------------------------
    def reset(self) -> "SimulationState":
        self.disruptions = []
        self.sequence = 0
        self.booked = build_baseline_entries()
        self.baseline = build_baseline()
        self.legacy = copy.deepcopy(self.baseline)
        self.legacy["source"] = "legacy_cascade"
        self.legacy["notes"] = ["No disruption injected - the cascade equals the booked plan."]
        self.rule_based = copy.deepcopy(self.baseline)
        self.rule_based["source"] = "rule_based"
        self.rule_based["notes"] = [
            "No disruption injected - the rule engine plan equals the booked plan."
        ]
        self.optimized = None
        self.solver_info = None
        # Hardware junction & sensor state
        self.sensor_seqs: Dict[str, int] = {}
        self.sensor_last_times: Dict[str, float] = {}
        self.last_sensor_event_time: Optional[float] = None
        self.hardware_state: Dict[str, Dict[str, Any]] = {
            "A": {"occupied": False, "train_id": "T101"},
            "B": {"occupied": False, "train_id": "T204"},
        }
        self.hardware_arrival_times: Dict[str, Optional[int]] = {"A": None, "B": None}
        self.hardware_signals: Dict[str, str] = {"A": "PROCEED", "B": "PROCEED"}
        self.hardware_reason: str = "Junction free. No conflicting movements."
        self.last_junction_decision: Optional[Dict[str, Any]] = None
        return self

    def process_sensor_event(self, event_data: Dict[str, Any]) -> Dict[str, Any]:
        """Process an incoming GPIO sensor event with seq-based idempotency."""
        import time
        from optimizer import optimize_junction_conflict

        source = str(event_data.get("source", ""))
        seq = int(event_data.get("seq", 0))
        block_id = str(event_data.get("block_id", "")).strip().upper()
        state = str(event_data.get("state", "")).strip().lower()
        now_ts = int(event_data.get("timestamp") or (time.time() * 1000))
        current_time = time.time()

        # Idempotency and hardened reboot handling:
        # 1. seq == last_seq: duplicate -> reject
        # 2. Check if a reboot occurred:
        #    a) seq < last_seq for this source, and (seq <= 3 or time_gap > 10.0s)
        #    b) seq <= 3 from any source while previous sources were advanced (> 3)
        # 3. Otherwise, if seq < last_seq within 10s: stale/replayed packet -> reject
        # 4. seq > last_seq: normal -> accept
        is_reboot = False
        if source in self.sensor_seqs:
            last_seq = self.sensor_seqs[source]
            last_time = self.sensor_last_times.get(source, current_time)
            time_gap = current_time - last_time

            if seq == last_seq:
                return {
                    "status": "acknowledged",
                    "seq": seq,
                    "action_taken": "duplicate_ignored",
                    "active_trains": self.get_active_hardware_trains(),
                }
            elif seq < last_seq:
                if seq <= 3 or time_gap > 10.0:
                    is_reboot = True
                else:
                    return {
                        "status": "acknowledged",
                        "seq": seq,
                        "action_taken": "duplicate_ignored",
                        "active_trains": self.get_active_hardware_trains(),
                    }
        else:
            if any(s > 3 for s in self.sensor_seqs.values()) and seq <= 3:
                is_reboot = True

        if is_reboot:
            old_info = dict(self.sensor_seqs)
            print(
                f"\n>> [SOURCE REBOOT DETECTED] source={source!r} new_seq={seq} previous_seqs={old_info} "
                f"- resetting ALL source seq trackers and clearing ALL track occupancy state.",
                flush=True,
            )
            self.sensor_seqs.clear()
            self.sensor_last_times.clear()
            self.hardware_state["A"]["occupied"] = False
            self.hardware_arrival_times["A"] = None
            self.hardware_state["B"]["occupied"] = False
            self.hardware_arrival_times["B"] = None

        self.sensor_seqs[source] = seq
        self.sensor_last_times[source] = current_time
        self.last_sensor_event_time = current_time

        # State transition according to hardware pin mapping
        # A1: Train A Approaching -> Approach Block A: occupied
        # A2: Train A Cleared Junction -> Approach Block A: free
        # B1: Train B Approaching -> Approach Block B: occupied
        # B2: Train B Cleared Junction -> Approach Block B: free
        if block_id == "A1":
            self.hardware_state["A"]["occupied"] = (state == "occupied")
            if state == "occupied":
                self.hardware_arrival_times["A"] = now_ts
        elif block_id == "A2":
            self.hardware_state["A"]["occupied"] = False
            self.hardware_arrival_times["A"] = None
        elif block_id == "B1":
            self.hardware_state["B"]["occupied"] = (state == "occupied")
            if state == "occupied":
                self.hardware_arrival_times["B"] = now_ts
        elif block_id == "B2":
            self.hardware_state["B"]["occupied"] = False
            self.hardware_arrival_times["B"] = None

        occ_a = self.hardware_state["A"]["occupied"]
        occ_b = self.hardware_state["B"]["occupied"]
        train_a = self.hardware_state["A"]["train_id"]
        train_b = self.hardware_state["B"]["train_id"]

        # Conflict resolution logic (Section 2.3 & 3.2)
        self.last_junction_decision = None
        if not occ_a and not occ_b:
            # Scenario 1: No trains approaching -> junction free
            self.hardware_signals = {"A": "PROCEED", "B": "PROCEED"}
            self.hardware_reason = "Junction free. No conflicting movements."
            action_taken = "state_updated"
            active_trains = []

        elif occ_a and not occ_b:
            # Scenario 2: Single train approaching on Approach A
            self.hardware_signals = {"A": "PROCEED", "B": "HOLD"}
            name_a = TRAIN_BY_ID[train_a]["name"]
            type_a = TRAIN_BY_ID[train_a]["type"]
            self.hardware_reason = f"Train A ({type_a} {train_a} - {name_a}) approaching on clear track. Signal PROCEED granted."
            action_taken = "signal_granted"
            active_trains = [train_a]

        elif occ_b and not occ_a:
            # Scenario 2: Single train approaching on Approach B
            self.hardware_signals = {"A": "HOLD", "B": "PROCEED"}
            name_b = TRAIN_BY_ID[train_b]["name"]
            type_b = TRAIN_BY_ID[train_b]["type"]
            self.hardware_reason = f"Train B ({type_b} {train_b} - {name_b}) approaching on clear track. Signal PROCEED granted."
            action_taken = "signal_granted"
            active_trains = [train_b]

        else:
            # Scenario 3: Dual train conflict (A1 + B1 active simultaneously)
            # Calculate dynamic arrival ready offsets (in minutes) from real sensor timestamps
            ts_a = self.hardware_arrival_times.get("A") or now_ts
            ts_b = self.hardware_arrival_times.get("B") or now_ts
            if ts_a <= ts_b:
                ready_a = 0
                ready_b = max(0, int(round((ts_b - ts_a) / 60000.0)))
            else:
                ready_b = 0
                ready_a = max(0, int(round((ts_a - ts_b) / 60000.0)))

            weight_a = TRAIN_BY_ID[train_a]["weight"]
            weight_b = TRAIN_BY_ID[train_b]["weight"]
            run_a = TRAIN_BY_ID[train_a]["run_min"][ROUTE_BLOCK_IDS[0]]
            run_b = TRAIN_BY_ID[train_b]["run_min"][ROUTE_BLOCK_IDS[0]]
            name_a = TRAIN_BY_ID[train_a]["name"]
            name_b = TRAIN_BY_ID[train_b]["name"]

            # Invoke CP-SAT 2-train junction optimizer
            solver_res = optimize_junction_conflict(
                ready_time_a=ready_a,
                ready_time_b=ready_b,
                weight_a=weight_a,
                weight_b=weight_b,
                run_time_a=run_a,
                run_time_b=run_b,
                headway=MIN_HEADWAY_MIN,
            )

            status_str = solver_res.get("status", "OPTIMAL")
            obj_val = solver_res.get("objective_value")
            wall_ms = solver_res.get("wall_time_ms")
            entry_a_lbl = format_minute(solver_res["entry_a"])
            entry_b_lbl = format_minute(solver_res["entry_b"])
            delay_a = solver_res["delay_a"]
            delay_b = solver_res["delay_b"]

            if solver_res["proceed_train"] == "A":
                self.hardware_signals = {"A": "PROCEED", "B": "HOLD"}
                self.hardware_reason = (
                    f"CP-SAT ({status_str}) prioritizes Train A ({train_a} {name_a}) at {entry_a_lbl}; "
                    f"holds Train B ({train_b} {name_b}) until {entry_b_lbl} (+{delay_b} min delay) "
                    f"[obj={obj_val}, {wall_ms}ms]."
                )
            else:
                self.hardware_signals = {"A": "HOLD", "B": "PROCEED"}
                self.hardware_reason = (
                    f"CP-SAT ({status_str}) prioritizes Train B ({train_b} {name_b}) at {entry_b_lbl}; "
                    f"holds Train A ({train_a} {name_a}) until {entry_a_lbl} (+{delay_a} min delay) "
                    f"[obj={obj_val}, {wall_ms}ms]."
                )

            self.last_junction_decision = {
                "ready_time_a": ready_a,
                "ready_time_b": ready_b,
                "weight_a": weight_a,
                "weight_b": weight_b,
                "entry_a": solver_res["entry_a"],
                "entry_b": solver_res["entry_b"],
                "delay_a": solver_res["delay_a"],
                "delay_b": solver_res["delay_b"],
                "proceed_train": solver_res["proceed_train"],
                "hold_train": solver_res["hold_train"],
                "objective_value": solver_res["objective_value"],
                "wall_time_ms": solver_res["wall_time_ms"],
            }

            action_taken = "conflict_evaluated"
            active_trains = [train_a, train_b]

        return {
            "status": "acknowledged",
            "seq": seq,
            "action_taken": action_taken,
            "active_trains": active_trains,
        }

    def get_active_hardware_trains(self) -> List[str]:
        trains = []
        if self.hardware_state["A"]["occupied"]:
            trains.append(self.hardware_state["A"]["train_id"])
        if self.hardware_state["B"]["occupied"]:
            trains.append(self.hardware_state["B"]["train_id"])
        return trains

    def get_hardware_block_state(self) -> Dict[str, Any]:
        """Advisory signal polling response for ESP32 and UI."""
        import time

        now_ms = int(time.time() * 1000)
        is_stale = False
        if self.last_sensor_event_time is not None:
            if time.time() - self.last_sensor_event_time > 5.0:
                is_stale = True

        blocks = [
            {
                "block_id": "A",
                "signal": self.hardware_signals.get("A", "PROCEED"),
                "train_id": self.hardware_state["A"]["train_id"],
            },
            {
                "block_id": "B",
                "signal": self.hardware_signals.get("B", "PROCEED"),
                "train_id": self.hardware_state["B"]["train_id"],
            },
        ]
        return {
            "timestamp": now_ms,
            "is_stale": is_stale,
            "blocks": blocks,
            "reason": self.hardware_reason,
        }

    def _recompute(self) -> None:
        """Rebuild every derived plan after a disruption / reset."""
        if self.disruptions:
            self.legacy = propagate_legacy(self.disruptions, self.booked)
            self.rule_based = plan_rule_based(self.disruptions, booked=self.booked)
        else:
            self.legacy = copy.deepcopy(self.baseline)
            self.legacy["source"] = "legacy_cascade"
            self.legacy["notes"] = ["No disruption injected - the cascade equals the booked plan."]
            self.rule_based = copy.deepcopy(self.baseline)
            self.rule_based["source"] = "rule_based"
            self.rule_based["notes"] = [
                "No disruption injected - the rule engine plan equals the booked plan."
            ]
        # Any earlier optimization is stale as soon as the inputs change.
        self.optimized = None
        self.solver_info = None

    def add_disruption(self, raw: Dict[str, Any]) -> Dict[str, Any]:
        disruption = normalise_disruption(raw)
        self.sequence += 1
        disruption["id"] = f"DIS-{self.sequence}"
        disruption["sequence"] = self.sequence
        self.disruptions.append(disruption)
        self._recompute()
        return disruption

    def set_optimized(self, schedule: Dict[str, Any], solver_info: Dict[str, Any]) -> None:
        self.optimized = schedule
        self.solver_info = solver_info

    # -- accessors ---------------------------------------------------------
    def schedule(self, name: str) -> Optional[Dict[str, Any]]:
        return {
            "baseline": self.baseline,
            "booked": self.baseline,
            "legacy_cascade": self.legacy,
            "legacy": self.legacy,
            "rule_based": self.rule_based,
            "optimized": self.optimized,
            "cp_sat": self.optimized,
        }.get(name)

    def active_name(self) -> str:
        """Which plan currently sits on the dispatcher's desk."""
        if self.optimized is not None:
            return "optimized"
        if self.disruptions:
            return "legacy_cascade"
        return "baseline"

    def active_schedule(self) -> Dict[str, Any]:
        return self.schedule(self.active_name())

    def is_optimized(self) -> bool:
        return self.optimized is not None

    # -- API payloads ------------------------------------------------------
    def snapshot(self) -> Dict[str, Any]:
        return {
            "meta": {
                "base_time": format_minute(0),
                "base_minute": BASE_MINUTE,
                "min_headway_min": MIN_HEADWAY_MIN,
                "min_dwell_min": MIN_DWELL_MIN,
                "horizon_min": HORIZON_MIN,
                "disclaimer": DISCLAIMER,
            },
            "topology": {
                "stations": STATIONS,
                "blocks": BLOCKS,
                "route": ROUTE_BLOCK_IDS,
                "booked_order": BOOKED_ORDER,
                "trains": [train_public_payload(train) for train in TRAINS],
            },
            "schedules": {
                "baseline": self.baseline,
                "legacy_cascade": self.legacy,
                "rule_based": self.rule_based,
                "optimized": self.optimized,
            },
            "simulation": {
                "active_schedule": self.active_name(),
                "has_disruptions": bool(self.disruptions),
                "is_optimized": self.is_optimized(),
                "disruptions": self.disruptions,
                "solver_info": self.solver_info,
            },
        }


_STATE: Optional[SimulationState] = None


def get_state() -> SimulationState:
    """Process wide singleton used by the FastAPI layer."""
    global _STATE
    if _STATE is None:
        _STATE = SimulationState()
    return _STATE
